### ISSUE TITLE
Problema ao inserir url em Link 

### ISSUE THREAD

**Issue by HeytorPires** [bernardoazevedo/my-url.online#1]
Olá Bernado.
Eu acabei me deparando com o seu projeto no tab news que até comentei, pois achei muito e ótimo, e por isso venho aqui para relatar um Problema que encontrei, e cabe a você acatar meu adendo como usuário.
Ao eu criar um Link para meu perfil, no campo Link, se eu colocar uma url que eu mesmo pego do navegador, ele concatena com o "https://", deixando assim a url com dois protocolos de transferência, impossibilitando eu acessar o link que criei futuramente, pois você deixou como padrão concatenar o protocolo de transferência com a url, o que não está errado, mas seria interessante você fazer uma validação antes de salvar o Link no banco, para assim independentemente se meu link estiver com o protocolo, ele salvar de uma forma que eu possa acessar futuramente  .
![bernado-01 png](https://github.com/user-attachments/assets/bfa13cd8-b65a-434d-b0bf-85f7711d28f3)
![bernado-02](https://github.com/user-attachments/assets/f728f721-25b9-4610-8fb0-0599b35412d8)

Gostária de um feedback, para saber como essa sugestão foi interpretada, e se foi bem aproveitada, Obrigado!
heytor.cacho29@gmail.com

**Comment by bernardoazevedo** [comment]
Opa Heytor, acabei de corrigir esse erro. Muito obrigado pela issue aberta!
